### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/khs-minithon.github.io#53]
Can we add the calendar? It has dates and times for stuff. It is a google calendar.
see towards the bottom of: http://fourdiamonds.donordrive.com/event/khs16 for the calendar. Let me know what links or whatever you need to implement it.

**Comment by JoseRoman** [comment]
I feel like this would be adding unnecessary stuff to the website since we already have a button that takes users to that page. If we are going to be showing almost everything in that page to the users that visit khsminithon.org then what is the point of having a button that takes them to it? 

I think there are more important issues we could be tackling such as the Logo which you kind of have been neglecting for about a month now (since Oct 22) and the Dancer Packet PDF which is currently a blank file in the website.

**Comment by theseanconn** [comment]
I mean the calendar itself. I was just showing that so you could see how it is on that page.
The logo will be here by december 11th. That is the deadline we have set. The dancer packet will be available thursday

**Comment by theseanconn** [comment]
The HTML calendar code is: https://calendar.google.com/calendar/embed?src=khsminithon%40gmail.com&ctz=America/New_York

**Comment by JoseRoman** [comment]
![image](https://cloud.githubusercontent.com/assets/4240075/11519538/162be018-9869-11e5-9cc4-a198e3bce40d.png)
